### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Josecholi** [ddosscripts/Getting-Started#1]
This isn't an issue but a question, are you sure crowncloud spoofs? I asked them and they said they didn't. If so, which plans spoof?

**Comment by ddosscripts** [comment]
They wouldn't say that they do.. It is against their terms of service. All plans _should_ spoof but honestly for premium hosting give me your discord.

**Comment by Josecholi** [comment]
my discord is Desmecito#3476

**Comment by Josecholi** [comment]
Yo friend my new discord Desmecito#0805
